### ISSUE TITLE
yarn run start:dist

### ISSUE THREAD

**Issue by 0xpbj** [happylinks/blrplt#2]
Hi @happylinks, thanks for putting together this boilerplate. I am having testing my build with your webpack files. I thought nodeExternals is supposed to exclude these folders for the server side rending? Do you have any suggestions on how I can get around this?

I am getting this error when I run 'yarn run start:dist'

> /Users/prabhaav/Development/blrplt: yarn run start:dist
yarn run v0.18.1
$ node ./build/server.js 
/Users/prabhaav/Development/blrplt/node_modules/hellojs/dist/hello.all.js:206
		redirect_uri: window.location.href.split('#')[0],
		              ^
> ReferenceError: window is not defined
    at Object.<anonymous> (/Users/prabhaav/Development/blrplt/node_modules/hellojs/dist/hello.all.js:206:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/prabhaav/Development/blrplt/build/server.js:1986:18)
    at __webpack_require__ (/Users/prabhaav/Development/blrplt/build/server.js:21:30)
error Command failed with exit code 1.

**Comment by happylinks** [comment]
Hee @prabhaav, sorry for the late response. 
Can you check what's on this line:
/Users/prabhaav/Development/blrplt/build/server.js:1986:18
Maybe it's an include in your code? You must make sure that browser-things like window aren't rendered when the server renders the application. You can prevent loading these parts bij checking the isBrowser global variable and conditionally rendering these parts.
Let me know if I can help you more.
